import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

/**
 * Geist Sans and Geist Mono fonts from Google Fonts
 * Geist Sans is used for body text and headings, while Geist Mono is used for code snippets and technical content.
 * Both fonts support Latin characters and are optimized for web use.
 * The fonts are loaded with CSS variables for easy integration with Tailwind CSS.
 * Later we can use these fonts in our components by applying the respective CSS variables to the className attribute.
 */
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/**
 * Metadata for the application
 * This metadata object defines the title and description of the web application.
 * The title is set to "Create Next App" and the description indicates that the app was generated by Create Next App.
 * This metadata can be used for SEO purposes and to provide information about the app in the browser tab.
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * @param param0 app/page.tsx etc to be inserted in this layout.
 * @returns
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    /**
     * en means page language is English for SEO purposes.
     * geistSans.variable and geistMono.variable are CSS variables for the fonts.
     * antialiased improves font rendering on some screens.
     */
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
